version: '3'
services:
  django:
    build: .
    restart: on-failure
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=northpole.settings.docker_development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=northpole_user
      - POSTGRES_PASSWORD=insecure
      - POSTGRES_DB=northpole-docker-development
      - COLLECT_STATIC=1
      - LOAD_FIXTURES
    volumes:
      - .:/django
      - static_volume:/django/static
      - media_volume:/django/media
    networks:
      - nginx_network
      - postgres_network
      - redis_network
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    command: ./start.sh

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=data
      - POSTGRES_USER=northpole_user
      - POSTGRES_PASSWORD=insecure
      - POSTGRES_DB=northpole-docker-development
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - postgres_network

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_volume:/data
    networks:
      - redis_network

  nginx:
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/django/static
      - media_volume:/django/media
    networks:
      - nginx_network
    depends_on:
      - django

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redis_volume:

networks:
  postgres_network:
    driver: bridge
  redis_network:
    driver: bridge
  nginx_network:
    driver: bridge
